import { test, expect, type Page } from '@playwright/test'

test.beforeEach(async ({ page }) => { await page.emulateMedia({ reducedMotion: 'reduce' }) })

async function receiveTicket(page: Page) {
  await page.getByRole('button', { name: '次へ', exact: true }).click()
  await page.getByRole('button', { name: '次へ', exact: true }).click()
  await page.getByRole('button', { name: '切符を受け取る', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'はじめての切符' })).toBeVisible()
}

async function readTravel(page: Page, demo = false) {
  return page.evaluate(key => JSON.parse(localStorage.getItem(key)!), `syasou.travel.v2${demo ? '.demo' : ''}`)
}

test('the demo starts with three varied tickets, receives a keepsake, and retains sample edits without reseeding', async ({ page }) => {
  await page.goto('/?demo=1')
  await page.getByRole('button', { name: '窓辺へ', exact: true }).click()
  const initial = await readTravel(page, true)
  expect(initial.tickets).toHaveLength(3)
  expect(new Set(initial.tickets.map((ticket: { scene: string }) => ticket.scene)).size).toBe(3)
  expect(initial.tickets.every((ticket: { kind: string }) => ticket.kind === 'sample')).toBe(true)
  await receiveTicket(page)
  await page.getByRole('button', { name: '手帳にしまう', exact: true }).click()
  await expect(page.getByRole('button', { name: '集めた切符を見る' })).toBeFocused()
  await page.getByRole('button', { name: '集めた切符を見る' }).click()
  for (const title of ['読みかけの本を、ひと章', '企画のラフを描く', '明日のことを手帳に']) {
    await page.getByRole('button', { name: '前の切符を見る' }).click()
    await expect(page.getByRole('textbox', { name: '切符に残す作業' })).toHaveValue(title)
    await expect(page.locator('.ticket-on-top .ticket-stamp')).toHaveText('SAMPLE')
  }
  await expect(page.getByRole('button', { name: '前の切符を見る' })).toBeDisabled()
  await page.getByRole('textbox', { name: '切符に残す作業' }).fill('テストで書き直した切符')
  await page.getByRole('button', { name: '切符の裏を見る' }).click()
  await expect(page.getByRole('textbox', { name: '切符のメモ' })).toHaveValue(/自分のペース/)
  await page.getByRole('textbox', { name: '切符のメモ' }).fill('裏にも書き残せた。')
  await page.reload()
  await expect(page.locator('.opening-screen')).toHaveCount(0)
  await expect(page.getByRole('dialog')).toHaveCount(0)
  const saved = await readTravel(page, true)
  expect(saved.tickets).toHaveLength(4)
  expect(saved.tickets.filter((ticket: { kind: string }) => ticket.kind === 'welcome')).toHaveLength(1)
  expect(saved.tickets[3].title).toBe('テストで書き直した切符')
  expect(saved.tickets[3].note).toBe('裏にも書き残せた。')
  expect(saved.journey.phase).toBe('idle')
  expect(await page.evaluate(() => localStorage.getItem('syasou.travel.v2'))).toBeNull()
})

test('demo entry isolates tickets, notes, preferences, onboarding and title state from the normal notebook', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '窓辺へ', exact: true }).click()
  await page.getByRole('button', { name: 'スキップ' }).click()
  await page.getByRole('button', { name: '旅の手帳を開く' }).click()
  await page.getByRole('textbox', { name: '手帳のメモ' }).fill('いつもの大切な下書き')
  await page.getByRole('button', { name: '乗車する', exact: true }).click()
  await page.getByRole('button', { name: '旅の手帳を開く' }).click()
  await page.getByRole('button', { name: '一時停止', exact: true }).click()
  const snapshot = () => page.evaluate(() => Object.fromEntries(['syasou.travel.v2', 'syasou.note.v1', 'syasou.preferences.v1', 'syasou.onboarding.v1'].map(key => [key, localStorage.getItem(key)])))
  const original = await snapshot()
  await page.goto('/?demo=1')
  await expect(page.getByRole('button', { name: '窓辺へ', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '窓辺へ', exact: true }).click()
  await receiveTicket(page)
  await page.getByRole('button', { name: '手帳にしまう', exact: true }).click()
  await page.getByRole('textbox', { name: '手帳のメモ' }).fill('おためしのメモ')
  await page.getByRole('button', { name: /列車の速さ/ }).click()
  expect(await snapshot()).toEqual(original)
  await page.goto('/')
  await expect(page.locator('.opening-screen')).toHaveCount(0)
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('button', { name: '旅の手帳を開く' }).click()
  await expect(page.getByRole('textbox', { name: '手帳のメモ' })).toHaveValue('いつもの大切な下書き')
  await expect(page.getByRole('button', { name: '旅を再開', exact: true })).toBeVisible()
  expect(await snapshot()).toEqual(original)
})

test('a keepsake awaiting storage survives reload and replay keeps the same edited ticket', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '窓辺へ', exact: true }).click()
  await receiveTicket(page)
  await page.getByRole('textbox', { name: '切符に残す作業' }).fill('わたしの最初の切符')
  const received = await readTravel(page)
  await page.reload()
  await expect(page.getByRole('dialog', { name: 'はじめての切符' })).toBeVisible()
  await expect(page.getByRole('textbox', { name: '切符に残す作業' })).toHaveValue('わたしの最初の切符')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button', { name: '集めた切符を見る' })).toBeFocused()
  await page.keyboard.press('Escape')
  await page.mouse.move(1370, 860)
  await page.getByRole('button', { name: '使い方を見る' }).click()
  await receiveTicket(page)
  await expect(page.getByRole('textbox', { name: '切符に残す作業' })).toHaveValue('わたしの最初の切符')
  const replayed = await readTravel(page)
  expect(replayed.tickets).toEqual(received.tickets)
  expect(replayed.journey).toEqual(received.journey)
  await page.getByRole('button', { name: '手帳にしまう', exact: true }).click()
  await page.reload()
  await expect(page.locator('.opening-screen')).toHaveCount(0)
  await expect(page.getByRole('dialog')).toHaveCount(0)
  expect((await readTravel(page)).pendingArrivalId).toBeNull()
})

test('a running journey keeps its deadline and note when the guide grants a keepsake', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '窓辺へ', exact: true }).click()
  await page.getByRole('button', { name: 'スキップ' }).click()
  await page.getByRole('button', { name: '旅の手帳を開く' }).click()
  await page.getByRole('textbox', { name: '手帳のメモ' }).fill('本当の作業')
  await page.getByRole('button', { name: '乗車する', exact: true }).click()
  const before = await readTravel(page)
  await page.mouse.move(1370, 860)
  await page.getByRole('button', { name: '使い方を見る' }).click()
  await receiveTicket(page)
  await page.getByRole('button', { name: '手帳にしまう', exact: true }).click()
  expect((await readTravel(page)).journey).toEqual(before.journey)
  await expect(page.getByRole('textbox', { name: '手帳のメモ' })).toHaveValue('本当の作業')
  await page.getByRole('button', { name: '旅を終える', exact: true }).click()
  await expect(page.getByRole('dialog', { name: '到着の切符' })).toBeVisible()
  await expect(page.getByRole('textbox', { name: '切符に残す作業' })).toHaveValue('本当の作業')
  const finished = await readTravel(page)
  expect(finished.tickets).toHaveLength(2)
  expect(finished.tickets[0].kind).toBeUndefined()
})

test('blocked storage still provides sample and welcome tickets for the current visit', async ({ page }) => {
  await page.addInitScript(() => { Storage.prototype.setItem = () => { throw new DOMException('Unavailable', 'QuotaExceededError') } })
  await page.goto('/?demo=1')
  await page.getByRole('button', { name: '窓辺へ', exact: true }).click()
  await receiveTicket(page)
  await expect(page.getByRole('alert')).toContainText('切符を保存できません')
  await page.getByRole('button', { name: '手帳にしまう', exact: true }).click()
  await page.getByRole('button', { name: '集めた切符を見る' }).click()
  await page.getByRole('button', { name: '前の切符を見る' }).click()
  await expect(page.getByRole('textbox', { name: '切符に残す作業' })).toHaveValue('読みかけの本を、ひと章')
})
