import { test, expect } from '@playwright/test'
import type { Page } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import { freezeClock as clock, waitForScene } from './scene'

test.beforeEach(async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.addInitScript(() => { sessionStorage.setItem('syasou.entered.v1', '1'); localStorage.setItem('syasou.onboarding.v1', 'true') })
})

async function book(page: Page) {
  await page.getByRole('button', { name: '旅の手帳を開く' }).click()
}

async function tickets(page: Page) {
  return page.evaluate(() => JSON.parse(localStorage.getItem('syasou.travel.v2')!).tickets)
}
async function putAway(page: Page) {
  await page.getByRole('button', { name: '手帳にしまう', exact: true }).click()
  await expect(page.getByRole('dialog', { name: '到着の切符' })).toHaveCount(0)
}

test('arrival saves a task once, supports both sides, and returns from the window view', async ({ page }) => {
  await clock(page)
  await page.goto('/')
  await waitForScene(page)
  await book(page)
  await page.getByRole('textbox', { name: '手帳のメモ' }).fill('第三章を書く\n雨の音を聴きながら。')
  await page.getByRole('button', { name: '乗車する', exact: true }).click()
  await page.clock.runFor(10)
  await page.getByRole('button', { name: '車窓を眺める' }).click()
  await page.clock.fastForward(25 * 60_000)
  await expect(page.getByRole('dialog', { name: '到着の切符' })).toBeVisible()
  await expect(page.getByRole('textbox', { name: '切符に残す作業' })).toHaveValue('第三章を書く')
  await expect(page.getByRole('button', { name: '手帳にしまう', exact: true })).toBeFocused()
  expect((await tickets(page))).toHaveLength(1)
  await page.getByRole('textbox', { name: '切符に残す作業' }).fill('第三章の下書き')
  await page.getByRole('button', { name: '切符の裏を見る' }).click()
  await expect(page.getByRole('textbox', { name: '切符のメモ' })).toHaveValue('第三章を書く\n雨の音を聴きながら。')
  await expect(page.getByRole('textbox', { name: '切符に残す作業' })).toHaveCount(0)
  await page.getByRole('textbox', { name: '切符のメモ' }).fill('続きは主人公の台詞から。')
  await page.keyboard.press('Escape')
  await page.clock.runFor(10)
  await expect(page.locator('.world')).not.toHaveClass(/at-window/)
  await expect(page.getByRole('button', { name: '旅の手帳を開く' })).toBeFocused()
  await page.clock.fastForward(8 * 60_000)
  expect((await tickets(page))).toHaveLength(1)
  await page.reload()
  await waitForScene(page)
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await book(page)
  await page.getByRole('button', { name: '集めた切符を見る' }).click()
  await expect(page.getByRole('textbox', { name: '切符に残す作業' })).toHaveValue('第三章の下書き')
  await page.getByRole('button', { name: '切符の裏を見る' }).click()
  await expect(page.getByRole('textbox', { name: '切符のメモ' })).toHaveValue('続きは主人公の台詞から。')
})

test('a journey completed while away is restored, with one persistent arrival and the actual arrival time', async ({ page }) => {
  await clock(page)
  await page.goto('/')
  await waitForScene(page)
  await book(page)
  await page.getByRole('textbox', { name: '手帳のメモ' }).fill('読みかけの本')
  await page.getByRole('button', { name: '乗車する', exact: true }).click()
  await page.clock.runFor(10)
  const original = await page.evaluate(() => JSON.parse(localStorage.getItem('syasou.travel.v2')!).journey)
  await page.clock.setSystemTime(new Date('2026-09-18T11:00:00+09:00'))
  await page.reload()
  await waitForScene(page)
  await expect(page.getByRole('dialog', { name: '到着の切符' })).toBeVisible()
  expect(await tickets(page)).toHaveLength(1)
  expect((await tickets(page))[0].arrivedAt).toBe(original.deadline)
  await page.reload()
  await waitForScene(page)
  await expect(page.getByRole('dialog', { name: '到着の切符' })).toBeVisible()
  expect(await tickets(page)).toHaveLength(1)
  await putAway(page)
  await page.reload()
  await waitForScene(page)
  await expect(page.getByRole('dialog')).toHaveCount(0)
  expect(await tickets(page)).toHaveLength(1)
})

test('untimed work becomes separate tickets and the pocket browses the task snapshots', async ({ page }) => {
  await page.goto('/')
  await waitForScene(page)
  await book(page)
  await page.getByRole('button', { name: '旅の設定', exact: true }).click()
  await page.getByRole('radio', { name: '時間を決めずに' }).click()
  await page.getByRole('radio', { name: '特急', exact: true }).click()
  await page.getByRole('button', { name: '手帳に戻る', exact: true }).first().click()
  for (const [i, title] of ['読書のつづき', '企画書を整える', '次の旅の計画'].entries()) {
    if (i) await book(page)
    await page.getByRole('textbox', { name: '手帳のメモ' }).fill(title)
    await page.getByRole('button', { name: i ? 'もう一度乗車する' : '乗車する', exact: true }).click()
    await book(page)
    await page.getByRole('button', { name: '旅を終える', exact: true }).click()
    await expect(page.getByRole('textbox', { name: '切符に残す作業' })).toHaveValue(title)
    await putAway(page)
  }
  expect(await tickets(page)).toHaveLength(3)
  expect((await tickets(page)).every((t: { speed: string }) => t.speed === 'express')).toBe(true)
  await book(page)
  await expect(page.locator('.ticket-pocket')).toHaveClass(/ticket-pocket-filled/)
  await page.getByRole('button', { name: '集めた切符を見る' }).click()
  await expect(page.getByRole('button', { name: '新しい切符を見る' })).toBeDisabled()
  await page.getByRole('button', { name: '前の切符を見る' }).click()
  await expect(page.getByRole('textbox', { name: '切符に残す作業' })).toHaveValue('企画書を整える')
  await page.getByRole('button', { name: '前の切符を見る' }).click()
  await expect(page.getByRole('textbox', { name: '切符に残す作業' })).toHaveValue('読書のつづき')
  await expect(page.getByRole('button', { name: '前の切符を見る' })).toBeDisabled()
  await page.getByRole('button', { name: '切符の裏を見る' }).click()
  await expect(page.getByRole('textbox', { name: '切符のメモ' })).toHaveValue('読書のつづき')
  await page.getByRole('button', { name: '手帳に戻る', exact: true }).click()
  await expect(page.getByRole('dialog', { name: '旅の手帳' })).toBeVisible()
})

test('a paused legacy journey migrates and does not award a ticket until it completes', async ({ page }) => {
  await clock(page)
  await page.addInitScript(() => {
    localStorage.setItem('syasou.journey.v1', JSON.stringify({ phase: 'focus', running: false, deadline: null, remaining: 60_000, focusMinutes: 25, restMinutes: 5 }))
  })
  await page.goto('/')
  await waitForScene(page)
  await page.clock.fastForward(24 * 60 * 60_000)
  expect(await tickets(page)).toHaveLength(0)
  await book(page)
  await expect(page.locator('.time-value')).toHaveText('01:00')
  await page.getByRole('button', { name: '旅を再開', exact: true }).click()
  await page.clock.runFor(10)
  await page.clock.fastForward(60_000)
  await expect(page.getByRole('dialog', { name: '到着の切符' })).toBeVisible()
  expect(await tickets(page)).toHaveLength(1)
})

test('the empty archive and both sides of a ticket are accessible and fit a laptop', async ({ page }) => {
  await page.setViewportSize({ width: 1280, height: 720 })
  await page.goto('/')
  await waitForScene(page)
  await book(page)
  await page.getByRole('button', { name: '集めた切符を見る' }).click()
  await expect(page.getByText('次の到着が、最初の一枚に。')).toBeVisible()
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: '乗車する', exact: true }).click()
  await book(page)
  await page.getByRole('button', { name: '旅を終える', exact: true }).click()
  const front = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa']).analyze()
  expect(front.violations).toEqual([])
  const fit = await page.locator('.ticket-tray-dialog').boundingBox()
  expect(fit!.x).toBeGreaterThanOrEqual(0)
  expect(fit!.y).toBeGreaterThanOrEqual(0)
  expect(fit!.x + fit!.width).toBeLessThanOrEqual(1280)
  expect(fit!.y + fit!.height).toBeLessThanOrEqual(720)
  await page.getByRole('button', { name: '切符の裏を見る' }).click()
  const back = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa']).analyze()
  expect(back.violations).toEqual([])
})

test('blocked storage keeps the in-memory ticket and reports the save failure', async ({ page }) => {
  await page.addInitScript(() => { Storage.prototype.setItem = () => { throw new DOMException('Unavailable', 'QuotaExceededError') } })
  await page.goto('/')
  await waitForScene(page)
  await book(page)
  await page.getByRole('textbox', { name: '手帳のメモ' }).fill('一歩だけ進める')
  await page.getByRole('button', { name: '乗車する', exact: true }).click()
  await book(page)
  await page.getByRole('button', { name: '旅を終える', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('切符を保存できません')
  await putAway(page)
  await book(page)
  await page.getByRole('button', { name: '集めた切符を見る' }).click()
  await expect(page.getByRole('textbox', { name: '切符に残す作業' })).toHaveValue('一歩だけ進める')
})
