import { expect, test, type Page } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import { freezeClock, waitForScene } from './scene'

test.beforeEach(async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.addInitScript(() => {
    for (const suffix of ['', '.demo']) {
      sessionStorage.setItem(`syasou.entered.v1${suffix}`, '1')
      localStorage.setItem(`syasou.onboarding.v1${suffix}`, 'true')
    }
  })
})

async function choose(page: Page, name: string) {
  await page.getByRole('button', { name: '眺めを選ぶ' }).click()
  await page.getByRole('radio', { name, exact: true }).click()
}
async function ready(page: Page) {
  await expect(page.locator('.snow-landscape')).toHaveAttribute('data-loaded', 'true')
}

test('views preserve a running journey and notes, support window mode, and restore on reload', async ({ page }) => {
  await freezeClock(page)
  await page.goto('/')
  await waitForScene(page)
  await page.getByRole('button', { name: '旅の手帳を開く' }).click()
  await page.getByRole('textbox', { name: '手帳のメモ' }).fill('雪を見ながら読書')
  await page.getByRole('button', { name: '乗車する', exact: true }).click()
  const before = await page.evaluate(() => JSON.parse(localStorage.getItem('syasou.travel.v2')!).journey)
  await choose(page, '雪原の窓')
  await ready(page)
  await page.getByRole('button', { name: '車窓を眺める' }).click()
  await expect(page.locator('.world')).toHaveClass(/at-window/)
  await choose(page, '遠くの列車')
  await ready(page)
  await expect(page.locator('.distant-train')).toBeVisible()
  await expect(page.getByRole('button', { name: '窓をひらく' })).toHaveCount(0)
  const after = await page.evaluate(() => JSON.parse(localStorage.getItem('syasou.travel.v2')!))
  expect(after.journey.id).toBe(before.id)
  expect(after.journey.deadline).toBe(before.deadline)
  expect(after.tickets).toHaveLength(0)
  await page.reload()
  await waitForScene(page)
  await ready(page)
  await expect(page.locator('.world')).toHaveAttribute('data-view', 'train')
  await page.getByRole('button', { name: '旅の手帳を開く' }).click()
  await expect(page.getByRole('dialog', { name: '旅の手帳' })).toBeVisible()
  await expect(page.getByRole('textbox', { name: '手帳のメモ' })).toHaveValue('雪を見ながら読書')
  await expect(page.getByRole('button', { name: '一時停止', exact: true })).toBeVisible()
})

test('the view picker supports keyboard selection, focus return, and Escape without leaving the current view', async ({ page }) => {
  await page.goto('/')
  await waitForScene(page)
  const trigger = page.getByRole('button', { name: '眺めを選ぶ' })
  await trigger.focus()
  await page.keyboard.press('Enter')
  await page.getByRole('radio', { name: '山あいの窓' }).focus()
  await page.keyboard.press('ArrowRight')
  await expect(page.getByRole('radio', { name: '雪原の窓' })).toBeFocused()
  await page.keyboard.press('Space')
  await ready(page)
  await expect(trigger).toBeFocused()
  await choose(page, '遠くの列車')
  await ready(page)
  await trigger.click()
  const accessibility = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa']).analyze()
  expect(accessibility.violations).toEqual([])
  await page.keyboard.press('Escape')
  await expect(page.locator('.view-picker')).toHaveCount(0)
  await expect(page.locator('.world')).toHaveAttribute('data-view', 'train')
  await expect(trigger).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(page.locator('.world')).toHaveAttribute('data-view', 'snow')
  await expect(page.getByRole('button', { name: '車窓を眺める' })).toBeFocused()
})

test('snow moves at different depths and stops for pause, hidden tabs, and reduced motion', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.goto('/')
  await waitForScene(page)
  await choose(page, '雪原の窓')
  await ready(page)
  const offsets = () => page.locator('.snow-strip').evaluateAll(nodes => nodes.map(node => new DOMMatrixReadOnly(getComputedStyle(node).transform).m41))
  const before = await offsets()
  await page.waitForTimeout(300)
  const after = await offsets()
  expect(after[0]).toBeLessThan(before[0])
  expect(before[2] - after[2]).toBeGreaterThan(before[0] - after[0])
  await page.getByRole('button', { name: '旅の手帳を開く' }).click()
  await page.getByRole('button', { name: '乗車する', exact: true }).click()
  await page.getByRole('button', { name: '旅の手帳を開く' }).click()
  await page.getByRole('button', { name: '一時停止', exact: true }).click()
  await expect(page.locator('.snow-landscape')).toHaveClass(/landscape-paused/)
  await page.waitForTimeout(100)
  const paused = await offsets()
  await page.waitForTimeout(250)
  expect(await offsets()).toEqual(paused)
  await page.getByRole('button', { name: '旅を再開', exact: true }).click()
  await expect.poll(offsets).not.toEqual(paused)
  await page.evaluate(() => {
    Object.defineProperty(document, 'hidden', { configurable: true, value: true })
    document.dispatchEvent(new Event('visibilitychange'))
  })
  await expect(page.locator('.snow-landscape')).toHaveClass(/landscape-paused/)
  await page.waitForTimeout(100)
  const hidden = await offsets()
  await page.waitForTimeout(250)
  expect(await offsets()).toEqual(hidden)
  await page.evaluate(() => {
    delete (document as unknown as { hidden?: boolean }).hidden
    document.dispatchEvent(new Event('visibilitychange'))
  })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await expect.poll(offsets).toEqual([0, 0, 0])
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await expect.poll(offsets).not.toEqual([0, 0, 0])
})

test('arrival from the exterior still delivers one ticket and returns to the seat', async ({ page }) => {
  await freezeClock(page)
  await page.goto('/')
  await waitForScene(page)
  await page.getByRole('button', { name: '旅の手帳を開く' }).click()
  await page.getByRole('button', { name: '乗車する', exact: true }).click()
  await choose(page, '遠くの列車')
  await ready(page)
  await page.clock.fastForward(25 * 60_000)
  await expect(page.getByRole('dialog', { name: '到着の切符' })).toBeVisible()
  await expect(page.locator('.snow-landscape')).toHaveClass(/landscape-paused/)
  await page.getByRole('button', { name: '手帳にしまう', exact: true }).click()
  await expect(page.locator('.world')).toHaveAttribute('data-view', 'forest')
  await expect(page.getByRole('button', { name: '旅の手帳を開く' })).toBeVisible()
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('syasou.travel.v2')!).tickets.length)).toBe(1)
})

test('missing artwork falls back to the current scenery and can be retried', async ({ page }) => {
  await page.route('**/scenery/overcast-sky.png', route => route.abort())
  await page.goto('/')
  await waitForScene(page)
  await choose(page, '雪原の窓')
  await expect(page.getByRole('alert')).toContainText('雪原の素材を読み込めませんでした')
  await expect(page.locator('.landscape')).not.toHaveAttribute('data-renderer', 'artwork')
  await page.unroute('**/scenery/overcast-sky.png')
  await page.getByRole('button', { name: 'もう一度読み込む' }).click()
  await ready(page)
  await expect(page.getByRole('alert')).toHaveCount(0)
})

test('demo scenery preferences stay separate and invalid preferences recover', async ({ page }) => {
  await page.goto('/')
  await waitForScene(page)
  await choose(page, '雪原の窓')
  await page.goto('/?demo=1')
  await waitForScene(page)
  await expect(page.locator('.world')).toHaveAttribute('data-view', 'forest')
  await choose(page, '遠くの列車')
  await page.goto('/')
  await waitForScene(page)
  await expect(page.locator('.world')).toHaveAttribute('data-view', 'snow')
  await page.evaluate(() => localStorage.setItem('syasou.view.v1', '"unknown-view"'))
  await page.reload()
  await waitForScene(page)
  await expect(page.locator('.world')).toHaveAttribute('data-view', 'forest')
})
